---
title: "The economic effects of trade policy uncertainty"

status: "Working Paper"
year: 2026
order: 2

description: >
  This paper studies the effects of unexpected changes in trade policy uncertainty (TPU) on the U.S. economy. Three measures of TPU are constructed using newspaper coverage, firms’ earnings calls, and tariff rates. Firm-level and aggregate macroeconomic data reveal that increases in TPU reduce business investment. The empirical results are interpreted through the lens of a two-country general equilibrium model with nominal rigidities and firms’ export participation decisions. News and increased uncertainty about higher future tariffs reduce investment and activity.

pdf: "https://www.sciencedirect.com/science/article/abs/pii/S0304393219302004?via%3Dihub"

citation:
  type: article-journal
  title: "The Economic Effects Of Trade Policy Uncertainty"

  author:
    - family: Caldara
      given: Dario
    - family: Iacoviello
      given: Matteo
    - family: Molligo
      given: Patrick
    - family: Prestipino
      given: Andrea
    - family: Raffo
      given: Andrea

  container-title: "Journal of Monetary Economics"
  volume: 109
  page: "38--59"
  issued:
    year: 2020
  DOI: "10.1016/j.jmoneco.2019.11.002"
  URL: "https://doi.org/10.1016/j.jmoneco.2019.11.002"
  status: "Published"

---

::: {.paper-page-links}

[Download PDF](https://doi.org/10.1016/j.jmoneco.2019.11.002){.btn .btn-primary}

:::

## Abstract

This paper studies the effects of unexpected changes in trade policy uncertainty (TPU) on the U.S. economy. Three measures of TPU are constructed using newspaper coverage, firms’ earnings calls, and tariff rates. Firm-level and aggregate macroeconomic data reveal that increases in TPU reduce business investment. The empirical results are interpreted through the lens of a two-country general equilibrium model with nominal rigidities and firms’ export participation decisions. News and increased uncertainty about higher future tariffs reduce investment and activity.

## Results
New measures of trade policy uncertainty are constructed using firm-level and aggregate data.

Trade policy uncertainty reduced U.S. investment by about 1.5% in 2018.

Open-economy DSGE Model with heterogeneous firms and nominal rigidities analyzes news and uncertainty about future tariffs.

## Citation

Caldara, Dario, Matteo Iacoviello, Patrick Molligo, Andrea Prestipino, and Andrea Raffo. "The economic effects of trade policy uncertainty." Journal of Monetary Economics 109 (2020): 38-59.